/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Corrida;

public class App {
    
    public static void main(String[] args) {
        Veiculo fusca = new Veiculo(new Motorfusca());
        Veiculo lamborghini = new Veiculo(new Motorlamborghini());
        Veiculo celta = new Veiculo(new Motorcelta());
        Veiculo ferrari = new Veiculo(new Motorferrari());
        
        System.out.println(fusca.acelerar());
        System.out.println(lamborghini.acelerar());
        System.out.println(celta.acelerar());
        System.out.println(ferrari.acelerar());
        
    }
}